/* Generated by tools/generate_registries.py; do not edit. */
#ifndef RADIO_EXPLORER_REGISTRY_DATA_H
#define RADIO_EXPLORER_REGISTRY_DATA_H
#include <stddef.h>
#include <stdint.h>
typedef struct __attribute__((packed)) { uint8_t prefix[6]; uint8_t name_offset[3]; } registry_ieee_record_t;
typedef struct __attribute__((packed)) { uint16_t key; uint8_t name_offset[3]; } registry_name_record_t;
typedef struct __attribute__((packed)) { uint8_t uuid[16]; uint8_t name_offset[3]; } registry_uuid_record_t;
extern const registry_ieee_record_t radio_ieee_ma_l[];
extern const size_t radio_ieee_ma_l_count;
extern const registry_ieee_record_t radio_ieee_ma_m[];
extern const size_t radio_ieee_ma_m_count;
extern const registry_ieee_record_t radio_ieee_ma_s[];
extern const size_t radio_ieee_ma_s_count;
extern const char radio_ieee_strings[];
extern const size_t radio_ieee_strings_size;
extern const registry_name_record_t radio_company_records[];
extern const size_t radio_company_records_count;
extern const registry_uuid_record_t radio_service_records[];
extern const size_t radio_service_records_count;
extern const registry_name_record_t radio_appearance_records[];
extern const size_t radio_appearance_records_count;
extern const char radio_registry_strings[];
extern const size_t radio_registry_strings_size;
#define RADIO_REGISTRY_BUILD_ID "24624d24cb55"
#endif
